language: python

python:
  - "2.7"
#  - "3.6"

os:
    - linux

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

matrix:
    fast_finish: true

install:
  - pip install -r pip-requirements

script:
  - cd python && $TEST_CMD


